const cardData=[
    { id:1,
    imgSrc:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/GURU_NANAK_DEV_ENGG_COLLEGE.jpg/3104px-GURU_NANAK_DEV_ENGG_COLLEGE.jpg",
    title:'Guru Nanak Dev Engg College',
     Address:"510L, Model Town Rd, Pritm Nagar, Model Town, Ludhiana, Punjab 141002",
     number:"Phone: 0161 242 3872",
     links:"https://collegedunia.com/college/1787-guru-nanak-girls-college-ludhiana/courses-fees"
   
},
{ id:2,
    imgSrc:"https://images.collegedunia.com/public/college_data/images/appImage/7573_CMCL_New.jpg",
    title:'Christian Medical College & Hospital',
     Address:"Brown Rd, CMC Campus, Ludhiana, Punjab 141008",
     number:"Phone: 0161 242 0072",
     links:"https://collegedunia.com/college/7573-christian-medical-college-cmc-ludhiana",
},
{ id:3,
    imgSrc:"https://englishtribuneimages.blob.core.windows.net/gallary-content/2022/2/2022_2$largeimg_1032379125.jpg",
     title:'S.C.D. Government College',
      Address:"WR6H+7MR, near Rose Garden, Rose garden, Civil Lines, Ludhiana, Punjab 141001",
      number:"Phone: 0161 244 4998",
      links:"https://scdgovtcollege.ac.in/",
},
{id:4,
    imgSrc:"https://emango.s3.amazonaws.com/media/cache/86/d9/86d98b29f4e0a5d90d22640c017669b3.jpg",
    title:'Ramgarhia Girls College',
     Address:"WV24+859, Vishkarma Main Road,Near Vishkarma Chowk, St Pura, Miller Ganj, Ludhiana, Punjab 141001",
     number:"Phone: 0161 242 3872",
     links:"https://collegedunia.com/college/3706-ramgarhia-girls-college-ludhiana/courses-fees"
},
{id:5,
   imgSrc :"https://content.jdmagicbox.com/comp/ludhiana/73/0161p161std6873/catalogue/government-college-for-women-bharat-nagar-ludhiana-colleges-2hpoka4.jpg?clr=666600",
      title:'Government College For Girls, Ludhiana',
       Address:"WR4V+779, Ferozpur Road, Rakh Bagh, near Bharat Nagar Chowk, Ludhiana, Punjab 141001",
       number:"Phone: 0161 244 96502",
       links:"https://gcgldh.org/",
},
{id:6,
    imgSrc :"https://images.shiksha.com/mediadata/images/1492584764phpaT86Tr_g.jpg",
       title:'Bhutta College of Engineering And Technology',
        Address: "One of the best Engineering College in Punjab. ... Bhutta, Ludhiana- 141206."        ,
        number:"Phone: 0161 242 95502",
        links:"https://gcgldh.org/",
 }]
export default cardData;